### Creating a Admin User ###

POST http://localhost:3005/auth/register
Content-Type: application/json

{
    "email": "newGuy54@example.com",
    "password": "BigrandomPass@12"
}

### Testing Excle to Json ###

GET http://localhost:3005/admin/dashboard/files